#!/bin/bash

alias tailf="tail -f"
alias l="ls"
alias ch="cd ~"
alias ll="ls -l"
alias vi="vim"
alias v="vim"
alias tmux="tmux -2"
alias t="tmux"
alias ta="tmux attach-session -t"
alias tn="tmux new -s"
alias wcl="wc -l"

export TERM=xterm-256color
[[ -s ~/.autojump/etc/profile.d/autojump.sh ]] && source ~/.autojump/etc/profile.d/autojump.sh

getftp(){
    file_name=$1
    curdir=`pwd`
    host=`hostname`
    echo ftp://${host}${curdir}/$file_name
}

function rm () {
  local file_path
  for file_path in "$@"; do
    # ignore any arguments
    if [[ "$file_path" = -* ]]; then :
    else
      local dst=${file_path##*/}
      # append the time if necessary
      while [ -e ~/.Trash/"$dst" ]; do
        dst="$dst "$(date +%H-%M-%S)
      done
      mv "$file_path" ~/.Trash/"$dst"
    fi
  done
}
